// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFx8KFXjhLUWNYHoOYQYoakUewnvD8qYw',
    appId: '1:14715182327:web:e5fc4a4cc78940e810c7f2',
    messagingSenderId: '14715182327',
    projectId: 'movies-app-c5c2b',
    authDomain: 'movies-app-c5c2b.firebaseapp.com',
    storageBucket: 'movies-app-c5c2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA701eqzNabIrxD73b0_pvlYSti1-6m2xs',
    appId: '1:14715182327:android:b46343dd72b955c710c7f2',
    messagingSenderId: '14715182327',
    projectId: 'movies-app-c5c2b',
    storageBucket: 'movies-app-c5c2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxMgUNDwUY0jDaYEL4CY1I7j8dAfzpCA',
    appId: '1:14715182327:ios:74284f0c9820eb8110c7f2',
    messagingSenderId: '14715182327',
    projectId: 'movies-app-c5c2b',
    storageBucket: 'movies-app-c5c2b.appspot.com',
    iosClientId: '14715182327-do9uq8vepbkdbthjj5g0kooelb8h1cu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHxMgUNDwUY0jDaYEL4CY1I7j8dAfzpCA',
    appId: '1:14715182327:ios:74284f0c9820eb8110c7f2',
    messagingSenderId: '14715182327',
    projectId: 'movies-app-c5c2b',
    storageBucket: 'movies-app-c5c2b.appspot.com',
    iosClientId: '14715182327-do9uq8vepbkdbthjj5g0kooelb8h1cu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
